# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a200tsbg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.cache/wt [current_project]
set_property parent.project_path E:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files E:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/ip/B_conv2/conv2_bias.coe
add_files E:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/ip/W_conv2/conv2_weight.coe
add_files E:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/ip/B_conv1/conv1_bias.coe
add_files E:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/ip/W_conv1/conv1_weight.coe
add_files E:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/ip/W_fc1/fc1_weight.coe
add_files E:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/ip/W_fc2/fc2_weight.coe
add_files E:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/ip/B_fc1/fc1_bias.coe
add_files E:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/ip/B_fc2/fc2_bias.coe
add_files E:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/ip/picture_784/image_pix22.coe
add_files E:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/ip/picture_784/image_pix11.coe
add_files E:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/ip/picture_784/image_pix44.coe
add_files E:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/ip/picture_784/image_pix414.coe
read_verilog -library xil_defaultlib {
  E:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/new/Multiply_adder.v
  E:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/new/conv1.v
  E:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/new/conv1_bias.v
  E:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/new/conv1_weight.v
  E:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/new/conv2.v
  E:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/new/conv2_bisa.v
  E:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/new/conv2_mutiply.v
  E:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/new/conv2_weight.v
  E:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/new/fc1.v
  E:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/new/fc1_bias.v
  E:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/new/fc2.v
  E:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/new/fc2_bias.v
  E:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/new/feature1_ram.v
  E:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/new/fifo_1000.v
  E:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/new/fifo_200.v
  E:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/new/image_data.v
  E:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/new/pooling.v
  E:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/new/cnn.v
}
read_ip -quiet E:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all e:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all e:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet E:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/ip/B_conv1/B_conv1.xci
set_property used_in_implementation false [get_files -all e:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/ip/B_conv1/B_conv1_ooc.xdc]

read_ip -quiet E:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/ip/B_conv2/B_conv2.xci
set_property used_in_implementation false [get_files -all e:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/ip/B_conv2/B_conv2_ooc.xdc]

read_ip -quiet E:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/ip/W_conv2/W_conv2.xci
set_property used_in_implementation false [get_files -all e:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/ip/W_conv2/W_conv2_ooc.xdc]

read_ip -quiet E:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/ip/W_conv1/W_conv1.xci
set_property used_in_implementation false [get_files -all e:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/ip/W_conv1/W_conv1_ooc.xdc]

read_ip -quiet E:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/ip/feature_ram/feature_ram.xci
set_property used_in_implementation false [get_files -all e:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/ip/feature_ram/feature_ram_ooc.xdc]

read_ip -quiet E:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/ip/W_fc1/W_fc1.xci
set_property used_in_implementation false [get_files -all e:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/ip/W_fc1/W_fc1_ooc.xdc]

read_ip -quiet E:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/ip/fifo_generator_200/fifo_generator_200.xci
set_property used_in_implementation false [get_files -all e:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/ip/fifo_generator_200/fifo_generator_200.xdc]
set_property used_in_implementation false [get_files -all e:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/ip/fifo_generator_200/fifo_generator_200_ooc.xdc]

read_ip -quiet E:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/ip/W_fc2/W_fc2.xci
set_property used_in_implementation false [get_files -all e:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/ip/W_fc2/W_fc2_ooc.xdc]

read_ip -quiet E:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/ip/B_fc1/B_fc1.xci
set_property used_in_implementation false [get_files -all e:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/ip/B_fc1/B_fc1_ooc.xdc]

read_ip -quiet E:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/ip/B_fc2/B_fc2.xci
set_property used_in_implementation false [get_files -all e:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/ip/B_fc2/B_fc2_ooc.xdc]

read_ip -quiet E:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/ip/picture_784/picture_784.xci
set_property used_in_implementation false [get_files -all e:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/ip/picture_784/picture_784_ooc.xdc]

read_ip -quiet E:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/ip/fifo_generator_1000/fifo_generator_1000.xci

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top cnn -part xc7a200tsbg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef cnn.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file cnn_utilization_synth.rpt -pb cnn_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
