# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/ip/B_fc1/B_fc1.xci
# IP: The module: 'B_fc1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/ip/B_fc1/B_fc1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'B_fc1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/ip/B_fc1/B_fc1.xci
# IP: The module: 'B_fc1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/个人/学习/大四上/智能芯片与系统设计综合实践/Comprehensive-practice-of-intelligent-chip-system-design/FPGA-proj-master/CNN_minist/CNN_minist.srcs/sources_1/ip/B_fc1/B_fc1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'B_fc1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
